### ISSUE TITLE
VF's not being assigned a GUID

### ISSUE THREAD

**Issue by therevoman** [openshift/sriov-network-device-plugin#20]
During testing it was identified that not all VF's are being assigned a GUID.  This is a problem for RDMA transfer and some of the perftest tools.  

**on server side**
ibv_devices
device node GUID
------ ----------------
mlx5_2 0000000000000000
mlx5_0 506b4b0300285028
mlx5_3 0000000000000000
mlx5_1 506b4b0300285034

**on client side**
ibv_devices
device node GUID
------ ----------------
mlx5_0 248a0703004bf0a8
mlx5_1 0000000000000000

Bug with additional details: https://github.com/linux-rdma/perftest/issues/64

**Comment by zshi-redhat** [comment]
sorry for late responding!
I believe this is fixed now in SR-IOV Operator[1] which initialize the VF node/port GUID immediately after VF gets created.
The PR fixes both IB and RoCE devices.

[1]:https://github.com/openshift/sriov-network-operator/pull/243
