### ISSUE TITLE
Helm chart for sriov-network-device-plugin 

### ISSUE THREAD

**Issue by jcpunk** [openshift/sriov-network-device-plugin#77]
## What would you like to be added?
Helm chart for sriov-network-device-plugin 

## What is the use case for this feature / enhancement?
When deploying things to my cluster I like to have helm charts so I can specifically select exactly which release is loaded and review what is running in my production clusters.

**Comment by SchSeba** [comment]
Hi this repo is only part of openshift project, and the openshift project only allow to deploy the device plugin as part of the sriov-network-operator via OLM.

if you want an helm chart for the device plugin please ask in the community project https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin
